### PR TITLE
Added the "stacktrace" command

### PR DESCRIPTION
**Pull request by agronholm**
This will be useful for debugging when the event loop thread is stuck.

### CODE REVIEW

**Comment by agronholm** [comment]
Can we get a new release with this command in it? Thanks.

**Comment by jettify** [comment]
sure, will do tonight

**Comment by jettify** [comment]
New version deployed on PyPI https://pypi.org/project/aiomonitor/0.3.1/

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
